### ISSUE TITLE
when delete the pic, show the error: TypeError: n.find(...) is null

### ISSUE THREAD

**Issue by cywforce** [KillerCodeMonkey/quill-image-resizor#1]
when delete the pic below, show the error: TypeError: n.find(...) is null

![微信图片_20241108224649](https://github.com/user-attachments/assets/7f2c24bf-8b42-47ed-997e-4d5545a90a57)
![微信图片_20241108224955](https://github.com/user-attachments/assets/f55e02aa-22e5-4db8-b4b9-3999343dd796)

**Comment by KillerCodeMonkey** [comment]
feel free to send a PR :).

**Comment by KillerCodeMonkey** [comment]
fixed in v1.3.2, if you use import Quill from 'quill' instead of window.Quill you can set now ImageResizor.QuillFind = Quill.find to get it work.

there is also an example in the readme and a code example in ngx-quill-example repo
